import Head from "next/head";
import Image from "next/image";
import Navbar from "@/components/organisms/navbar/Navbar";


export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        <Navbar />
        <div className="container mx-auto">
          <Image
            src={"/Charity-scaled.jpeg"}
            height={100}
            width={100}
            className="w-full h-80 object-cover"
          />
          <div className="flex flex-col mt-10">
            <span className="text-3xl font-bold text-center">
              Empowering Lives: Your Source for Personal Growth and Support
            </span>
            <span className="text-lg mt-5 text-center">
              Welcome to our website, a dedicated platform committed to helping
              individuals discover their potential, overcome challenges, and
              lead fulfilling lives. We believe that everyone deserves support
              and guidance, which is why we offer a wide range of resources and
              services tailored to empower you on your journey towards personal
              growth and well-being. Whether you're seeking practical advice,
              inspiration, or a supportive community, our website is here to
              provide the tools and knowledge you need to thrive. Together,
              let's embark on a transformative path, unlock your true potential,
              and create a brighter future.
            </span>
          </div>
        </div>
      </main>
    </>
  );
}
